### ISSUE TITLE
Program don't compile on r111

### ISSUE THREAD

**Issue by ColinPeyrat** [luruke/magicshader#8]
I get this error with MagicShader on the r111 :
```
Uncaught TypeError: Cannot read property 'getUniforms' of undefined
    at setProgram (three.module.js:25208)
    at Renderer.WebGLRenderer.renderBufferDirect (three.module.js:24204)
    at renderObject (three.module.js:24973)
    at renderObjects (three.module.js:24943)
    at Renderer.WebGLRenderer.render (three.module.js:24720)
    at WebGL.onTick (WebGL.js:79)
```

It seems to refer to this line on the `WebGLRenderer` : https://github.com/mrdoob/three.js/blob/r111/src/renderers/WebGLRenderer.js#L1721

Maybe it's linked with the change of `Material.needsUpdate` and the new `Material.version` introduced in r111 :https://github.com/mrdoob/three.js/wiki/Migration-Guide#r110--r111

I would be happy to help! Also, thanks for this library it's awesome!

**Comment by luruke** [comment]
Hey @ColinPeyrat , thanks for this!

I just tried to a basic example (the one on this repo - https://github.com/luruke/magicshader/tree/master/example) and seems working correctly with r111.

Can you send over a little demo to replicate the bug?
Merci!

**Comment by ColinPeyrat** [comment]
Sure ! Here it is : https://codesandbox.io/s/morning-frog-mmr13?fontsize=14&hidenavigation=1&theme=dark

**Comment by luruke** [comment]
@ColinPeyrat I couldn't replicate the issue locally...

You tested only on codesandbox?

Anyway, I've updated the threejs dependency on the package, and if you use `0.1.4` package seems working on codesandbox now

**Comment by ColinPeyrat** [comment]
@luruke I've found this issue locally, and replicate in codesandbox for the demo purpose !

But now it seems working both on codesandbox and locally, thanks !
